import { SPEC, LANGS, type CommandSpec, type OptionSpec } from "./spec";

function flagsForCommand(cmd: CommandSpec): string[] {
  return cmd.options.map((o) => o.flag);
}

function optionWordList(opts: OptionSpec[]): string {
  return opts.map((o) => o.flag).join(" ");
}

// Emits a `case` arm matching every option that takes a value, completing the
// appropriate word list, file glob, or default file completion. Falls through
// to the wider option-name completion otherwise.
function emitValueArms(cmd: CommandSpec, indent: string): string {
  const lines: string[] = [];
  for (const opt of cmd.options) {
    if (!opt.takes || opt.takes === "text") continue;
    const flags = [opt.flag];
    if (opt.takes === "lang") {
      lines.push(`${indent}${flags.join("|")})`);
      lines.push(`${indent}  COMPREPLY=( $(compgen -W "$__tl_langs" -- "$cur") )`);
      lines.push(`${indent}  return ;;`);
    } else if (opt.takes === "choice" && opt.choices) {
      lines.push(`${indent}${flags.join("|")})`);
      lines.push(`${indent}  COMPREPLY=( $(compgen -W "${opt.choices.join(" ")}" -- "$cur") )`);
      lines.push(`${indent}  return ;;`);
    } else if (opt.takes === "path") {
      lines.push(`${indent}${flags.join("|")})`);
      lines.push(`${indent}  compopt -o default 2>/dev/null; COMPREPLY=(); return ;;`);
    }
    // "value" takes any string — fall through to no completion.
  }
  return lines.join("\n");
}

function emitSubcommandHandler(parent: string, sub: CommandSpec): string {
  const fnName = `_tl_${parent}_${sub.name}`;
  const allFlags = optionWordList(sub.options);
  const valueArms = emitValueArms(sub, "    ");
  const positionalArm = (() => {
    const pos = sub.positionals?.[0];
    if (!pos) return "";
    if (pos.takes === "path") {
      return `  if [[ "$cur" != -* ]]; then compopt -o default 2>/dev/null; COMPREPLY=(); return; fi`;
    }
    if (pos.takes === "choice" && pos.choices) {
      return `  if [[ "$cur" != -* ]]; then COMPREPLY=( $(compgen -W "${pos.choices.join(" ")}" -- "$cur") ); return; fi`;
    }
    return "";
  })();

  return `${fnName}() {
  case "$prev" in
${valueArms || "    *) ;;"}
  esac
${positionalArm}
  COMPREPLY=( $(compgen -W "${allFlags}" -- "$cur") )
}`;
}

function emitCommandHandler(cmd: CommandSpec): string {
  const fnName = `_tl_${cmd.name}`;

  if (cmd.subcommands && cmd.subcommands.length > 0) {
    const subNames = cmd.subcommands.map((s) => s.name).join(" ");
    const subDispatchArms = cmd.subcommands
      .map((s) => `      ${s.name}) _tl_${cmd.name}_${s.name}; return ;;`)
      .join("\n");
    const subHandlers = cmd.subcommands.map((s) => emitSubcommandHandler(cmd.name, s)).join("\n\n");

    return `${fnName}() {
  local sub=""
  local i
  for ((i=2; i < cword; i++)); do
    case "\${words[i]}" in
      -*) ;;
      *) sub="\${words[i]}"; break ;;
    esac
  done
  if [[ -z "$sub" ]]; then
    COMPREPLY=( $(compgen -W "${subNames}" -- "$cur") )
    return
  fi
  case "$sub" in
${subDispatchArms}
  esac
}

${subHandlers}`;
  }

  // Leaf command (no subcommands)
  const allFlags = optionWordList(cmd.options);
  const valueArms = emitValueArms(cmd, "    ");
  const pos = cmd.positionals?.[0];
  let positionalArm = "";
  if (pos) {
    if (pos.takes === "choice" && pos.choices) {
      positionalArm = `  if [[ "$cur" != -* ]]; then COMPREPLY=( $(compgen -W "${pos.choices.join(" ")}" -- "$cur") ); return; fi`;
    } else if (pos.takes === "path") {
      positionalArm = `  if [[ "$cur" != -* ]]; then compopt -o default 2>/dev/null; COMPREPLY=(); return; fi`;
    }
  }
  return `${fnName}() {
  case "$prev" in
${valueArms || "    *) ;;"}
  esac
${positionalArm}
  COMPREPLY=( $(compgen -W "${allFlags}" -- "$cur") )
}`;
}

export function generateBash(): string {
  const topNames = SPEC.commands.map((c) => c.name).join(" ");
  const topDispatch = SPEC.commands
    .map((c) => `    ${c.name}) _tl_${c.name}; return ;;`)
    .join("\n");
  const handlers = SPEC.commands.map(emitCommandHandler).join("\n\n");
  const langs = LANGS.join(" ");

  return `# bash completion for tl
# Generated by \`tl completion bash\`. Do not edit manually.
#
# Install:
#   eval "$(tl completion bash)"          # current shell
#   tl completion bash >> ~/.bashrc       # persistent (per-user)
#   tl completion bash | sudo tee /etc/bash_completion.d/tl > /dev/null   # system-wide

__tl_langs="${langs}"

_tl() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  words=("\${COMP_WORDS[@]}")
  cword=$COMP_CWORD

  # Find first non-option word after \`tl\` to decide which command we're in.
  local cmd=""
  local i
  for ((i=1; i < cword; i++)); do
    case "\${words[i]}" in
      -*) ;;
      *) cmd="\${words[i]}"; break ;;
    esac
  done

  if [[ -z "$cmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--help -h --version -V" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "${topNames}" -- "$cur") )
    fi
    return
  fi

  case "$cmd" in
${topDispatch}
  esac
}

${handlers}

complete -F _tl tl
`;
}
