import { SUPPORTED_LANGUAGES } from "@translate-local/shared/constants";
import { SPEC, type CommandSpec, type OptionSpec, type PositionalSpec } from "./spec";

// Tokens emitted into bash unquoted (compgen -W "...") or into case patterns
// (case "$prev" in <token>)) must not contain shell metacharacters. Limit to
// flag-name / choice-value characters so a future SPEC entry with a quote, $,
// backtick, or glob char fails the build instead of silently injecting.
const SAFE_BASH_TOKEN = /^[A-Za-z0-9_.\-]+$/;
function assertSafeBashToken(s: string, kind: string): string {
  if (!SAFE_BASH_TOKEN.test(s)) {
    throw new Error(`Unsafe bash token (${kind}): ${JSON.stringify(s)}`);
  }
  return s;
}

function optionWordList(opts: OptionSpec[]): string {
  return opts.map((o) => assertSafeBashToken(o.flag, "flag")).join(" ");
}

function emitValueArms(cmd: CommandSpec, indent: string): string {
  const lines: string[] = [];
  for (const opt of cmd.options) {
    if (!opt.takes || opt.takes === "text") continue;
    const flag = assertSafeBashToken(opt.flag, "flag");
    if (opt.takes === "lang") {
      lines.push(`${indent}${flag})`);
      lines.push(`${indent}  COMPREPLY=( $(compgen -W "$__tl_langs" -- "$cur") )`);
      lines.push(`${indent}  return ;;`);
    } else if (opt.takes === "choice" && opt.choices) {
      const choices = opt.choices.map((c) => assertSafeBashToken(c, "choice")).join(" ");
      lines.push(`${indent}${flag})`);
      lines.push(`${indent}  COMPREPLY=( $(compgen -W "${choices}" -- "$cur") )`);
      lines.push(`${indent}  return ;;`);
    } else if (opt.takes === "path") {
      lines.push(`${indent}${flag})`);
      lines.push(`${indent}  compopt -o default 2>/dev/null; COMPREPLY=(); return ;;`);
    }
    // "value" takes any string — fall through to no completion.
  }
  return lines.join("\n");
}

function emitPositionalGuard(pos: PositionalSpec | undefined): string {
  if (!pos) return "";
  if (pos.takes === "choice" && pos.choices) {
    const choices = pos.choices.map((c) => assertSafeBashToken(c, "choice")).join(" ");
    return `  if [[ "$cur" != -* ]]; then COMPREPLY=( $(compgen -W "${choices}" -- "$cur") ); return; fi`;
  }
  if (pos.takes === "path") {
    return `  if [[ "$cur" != -* ]]; then compopt -o default 2>/dev/null; COMPREPLY=(); return; fi`;
  }
  return "";
}

function emitSubcommandHandler(parent: string, sub: CommandSpec): string {
  assertSafeBashToken(parent, "command");
  assertSafeBashToken(sub.name, "subcommand");
  const fnName = `_tl_${parent}_${sub.name}`;
  const allFlags = optionWordList(sub.options);
  const valueArms = emitValueArms(sub, "    ");
  const positionalArm = emitPositionalGuard(sub.positionals?.[0]);

  return `${fnName}() {
  case "$prev" in
${valueArms || "    *) ;;"}
  esac
${positionalArm}
  COMPREPLY=( $(compgen -W "${allFlags}" -- "$cur") )
}`;
}

function emitCommandHandler(cmd: CommandSpec): string {
  assertSafeBashToken(cmd.name, "command");
  const fnName = `_tl_${cmd.name}`;

  if (cmd.subcommands && cmd.subcommands.length > 0) {
    const subNames = cmd.subcommands.map((s) => assertSafeBashToken(s.name, "subcommand")).join(" ");
    const subDispatchArms = cmd.subcommands
      .map((s) => `      ${s.name}) _tl_${cmd.name}_${s.name}; return ;;`)
      .join("\n");
    const subHandlers = cmd.subcommands.map((s) => emitSubcommandHandler(cmd.name, s)).join("\n\n");

    // Find the parent command's position (skipping any leading top-level flags),
    // then look for the first non-flag word AFTER it. Mirrors the top-level _tl()
    // loop so future top-level flags (e.g. `tl --verbose glossary add`) don't
    // misalign subcommand detection.
    return `${fnName}() {
  local parent_idx=-1
  local j
  for ((j=1; j < cword; j++)); do
    case "\${words[j]}" in
      -*) ;;
      ${cmd.name}) parent_idx=$j; break ;;
      *) ;;
    esac
  done
  local sub=""
  local i
  for ((i=parent_idx+1; i < cword; i++)); do
    case "\${words[i]}" in
      -*) ;;
      *) sub="\${words[i]}"; break ;;
    esac
  done
  if [[ -z "$sub" ]]; then
    COMPREPLY=( $(compgen -W "${subNames}" -- "$cur") )
    return
  fi
  case "$sub" in
${subDispatchArms}
  esac
}

${subHandlers}`;
  }

  const allFlags = optionWordList(cmd.options);
  const valueArms = emitValueArms(cmd, "    ");
  const positionalArm = emitPositionalGuard(cmd.positionals?.[0]);
  return `${fnName}() {
  case "$prev" in
${valueArms || "    *) ;;"}
  esac
${positionalArm}
  COMPREPLY=( $(compgen -W "${allFlags}" -- "$cur") )
}`;
}

export function generateBash(): string {
  const topNames = SPEC.commands.map((c) => assertSafeBashToken(c.name, "command")).join(" ");
  const topDispatch = SPEC.commands
    .map((c) => `    ${c.name}) _tl_${c.name}; return ;;`)
    .join("\n");
  const handlers = SPEC.commands.map(emitCommandHandler).join("\n\n");
  const langs = SUPPORTED_LANGUAGES.join(" ");

  return `# bash completion for tl
# Generated by \`tl completion bash\`. Do not edit manually.
#
# Install:
#   eval "$(tl completion bash)"          # current shell
#   tl completion bash >> ~/.bashrc       # persistent (per-user)
#   tl completion bash | sudo tee /etc/bash_completion.d/tl > /dev/null   # system-wide

__tl_langs="${langs}"

_tl() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  words=("\${COMP_WORDS[@]}")
  cword=$COMP_CWORD

  # Find first non-option word after \`tl\` to decide which command we're in.
  local cmd=""
  local i
  for ((i=1; i < cword; i++)); do
    case "\${words[i]}" in
      -*) ;;
      *) cmd="\${words[i]}"; break ;;
    esac
  done

  if [[ -z "$cmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--help -h --version -V" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "${topNames}" -- "$cur") )
    fi
    return
  fi

  case "$cmd" in
${topDispatch}
  esac
}

${handlers}

complete -F _tl tl
`;
}
