import { SUPPORTED_LANGUAGES } from "@translate-local/shared/constants";
import { SPEC, type CommandSpec, type OptionSpec, type PositionalSpec } from "./spec";

// Escape characters that have special meaning inside a fish single-quoted string.
function fq(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function flagBareName(flag: string): string {
  return flag.replace(/^-+/, "");
}

function isShortFlag(flag: string): boolean {
  return /^-[^-]$/.test(flag);
}

function flagSwitches(flag: string): string {
  return isShortFlag(flag) ? `-s ${flagBareName(flag)}` : `-l ${flagBareName(flag)}`;
}

// Fish: -r requires an argument, -F asks for default file completion. Per-extension
// filtering is intentionally skipped — fish's globbing inside `-a` is fragile across
// versions and user-typed paths can be anywhere on disk.
const PATH_ARG = "-r -F";

function emitOptionLine(condition: string, opt: OptionSpec): string {
  const desc = fq(opt.description);
  const sw = flagSwitches(opt.flag);
  if (!opt.takes) {
    return `complete -c tl -n '${condition}' ${sw} -d '${desc}'`;
  }
  switch (opt.takes) {
    case "lang":
      return `complete -c tl -n '${condition}' ${sw} -x -a "$__tl_langs" -d '${desc}'`;
    case "choice":
      return `complete -c tl -n '${condition}' ${sw} -x -a '${(opt.choices ?? []).join(" ")}' -d '${desc}'`;
    case "path":
      return `complete -c tl -n '${condition}' ${sw} ${PATH_ARG} -d '${desc}'`;
    case "value":
    case "text":
      return `complete -c tl -n '${condition}' ${sw} -x -d '${desc}'`;
    default: {
      const _exhaustive: never = opt.takes;
      throw new Error(`Unhandled ArgKind: ${String(_exhaustive)}`);
    }
  }
}

function emitPositionalLine(condition: string, pos: PositionalSpec): string {
  if (pos.takes === "choice" && pos.choices) {
    return `complete -c tl -n '${condition}' -x -a '${pos.choices.join(" ")}'`;
  }
  if (pos.takes === "path") {
    return `complete -c tl -n '${condition}' -F`;
  }
  if (pos.takes === "lang") {
    return `complete -c tl -n '${condition}' -x -a "$__tl_langs"`;
  }
  return ""; // free-text positional — no completion to add
}

function topLevelCondition(): string {
  return "__fish_use_subcommand";
}

// The `not __fish_seen_subcommand_from <subs>` mask prevents subcommand names
// from being suggested again once one has been chosen.
function inCommandCondition(cmdName: string, subNames: string[] = []): string {
  if (subNames.length === 0) {
    return `__fish_seen_subcommand_from ${cmdName}`;
  }
  return `__fish_seen_subcommand_from ${cmdName}; and not __fish_seen_subcommand_from ${subNames.join(" ")}`;
}

function inSubcommandCondition(parent: string, sub: string): string {
  return `__fish_seen_subcommand_from ${parent}; and __fish_seen_subcommand_from ${sub}`;
}

function emitCommand(cmd: CommandSpec): string {
  const lines: string[] = [];
  lines.push(`complete -c tl -n '${topLevelCondition()}' -a '${cmd.name}' -d '${fq(cmd.description)}'`);

  if (cmd.subcommands && cmd.subcommands.length > 0) {
    const subNames = cmd.subcommands.map((s) => s.name);
    for (const sub of cmd.subcommands) {
      lines.push(
        `complete -c tl -n '${inCommandCondition(cmd.name, subNames)}' -a '${sub.name}' -d '${fq(sub.description)}'`,
      );
    }
    for (const sub of cmd.subcommands) {
      const cond = inSubcommandCondition(cmd.name, sub.name);
      for (const opt of sub.options) {
        lines.push(emitOptionLine(cond, opt));
      }
      for (const pos of sub.positionals ?? []) {
        const line = emitPositionalLine(cond, pos);
        if (line) lines.push(line);
      }
    }
  } else {
    const cond = inCommandCondition(cmd.name);
    for (const opt of cmd.options) {
      lines.push(emitOptionLine(cond, opt));
    }
    for (const pos of cmd.positionals ?? []) {
      const line = emitPositionalLine(cond, pos);
      if (line) lines.push(line);
    }
  }

  return lines.join("\n");
}

export function generateFish(): string {
  const langArr = SUPPORTED_LANGUAGES.join(" ");
  const blocks = SPEC.commands.map(emitCommand).join("\n\n");

  return `# fish completion for tl
# Generated by \`tl completion fish\`. Do not edit manually.
#
# Install:
#   tl completion fish > ~/.config/fish/completions/tl.fish
#
# After install, restart fish or run: source ~/.config/fish/completions/tl.fish

set -l __tl_langs ${langArr}

# Disable fish's default file completion — we control completions explicitly.
complete -c tl -f

# Global flags
complete -c tl -l help -d 'Show help'
complete -c tl -s h -d 'Show help'
complete -c tl -l version -d 'Show version'
complete -c tl -s V -d 'Show version'

${blocks}
`;
}
